"""Lane-aligned binary hop-0 ensemble. Never emits Lane event classes."""
import math,re
from .jev_acceptance import sha
from .jev_lane_contract import RUBRIC, CONTRACT_VERSION
VERSION='lane-hop0-v7'
QUESTIONS={
 'q5':{'type':'choice','instructions':RUBRIC,'criteria':{
  'change':'A specific new fact changes a tradable constraint, or a verified physical/legal regime break. Includes committed company expansion, actual results/guidance, deal announcement/cancellation, approval, court ruling, leadership/control, financing, actual disruption, official data or concrete new policy path.',
  'weather':'A known condition/tape reprint, interpretation, generic Fed/war/commodity color or public objective without a concrete new change.',
  'junk':'Advice/picks, price targets without company print/guidance, preview, roundup, transcript, feature, amenities, tiny subsidiary, unlinked local story or vague teaser.',
  'rumor':'Only speculation, hopes, leak, reportedly warned or hypothetical outcome without established event.'}},
 'action':{'type':'noul','instructions':'Is a concrete corporate, legal, operational, supply or funding constraint newly changed or committed in the supplied headline? Judge actual event, not generic financial relevance.', 'criteria':{'true':'An identifiable company/authority announces or executes a capacity change, leadership appointment/departure, binding deal or cancellation, buyback/financing/distress, gate/approval, legal ruling/probe, production decision, actual strike/disruption, new sanction/tariff/order or forced flow. A named listed firm committing to double data centers counts.','false':'Only market price, company opinion, analyst rating/target, uncommitted hopes/proposals, lawmakers urging, routine amenity/subsidiary, advice, preview, feature or no identifiable material change.'}},
 'print':{'type':'noul','instructions':'Does the supplied headline establish an actual new company result/guidance or official macro/production print? Do not confuse market prices, target prices, valuations or existing ownership with prints.', 'criteria':{'true':'Actual released earnings profit/revenue/growth/beat/miss, company guidance raised/cut or quantitative forecast newly issued, official inflation/jobs/GDP/retail/inventory data released, company production figures. A named earnings snapshot/release is actual results, not a preview.','false':'Analyst price target, share price/valuation, generic mentions of guidance/earnings without result, call transcript/highlights, future earnings preview, investor opinion or old unchanged fact.'}},
 'policy_path':{'type':'noul','instructions':'Is an authoritative policymaker stating a concrete NEW policy path, not general color? Freshness refers to supplied prior-event evidence; do not invent it.', 'criteria':{'true':'A named central-bank decision-maker announces a rate decision or specific new hike/cut path; an empowered government/OPEC actor commits a concrete supply/fiscal/trade/legal action. First-time Warsh says another hike is possible counts.','false':'Inflation objective, generic hawkishness, puts country on alert, pivotal moment, expert warning, rate odds, lawmakers urging, reportedly warned, hoped-for truce, or a rewrite of an already-scored statement.'}},
 'mechanism':{'type':'noul','instructions':'Is there an identifiable listed-company, US macro, global commodity/sector or US supply-chain channel changed by the reported event?', 'criteria':{'true':'A named listed company or broad macro/sector/commodity decision/print, financing/control/production/operations/legal gate. A foreign listed earnings print counts for further investigation. US relevance may be indirect through supply chains.','false':'Only sport/crime/monarchy/personal finance, local unrelated small business/flood, tiny subsidiary, unnamed minor recall or amenity promotion with no relevant listed channel.'}}
}

QUESTIONS['reported_fact']={'type':'noul','instructions':'Ignore framing and identify the actual underlying fact supplied. Is there a concrete report of an actual event/result with a potential market constraint? Do not select an event class. Do not require a numeric figure when an actual result direction or discrete event is explicit.', 'criteria':{'true':'Actual company earnings beat/miss/profit/revenue growth/decline or blowout/record quarter; released official economic data even unchanged/in-line; issued or cut/raised company guidance; actual central-bank rate decision including a hold; appointment, departure or death of a consequential corporate leader; a legal trial starts, lawsuit/settlement/ruling/probe; an authority sets an operative trade deadline or new rule; actual company customer losses/operational changes; funding, buybacks, acquisition/asset sale, committed capacity, trial result, approval, recall, cyberattack or an operational disruption. A stated event can sit inside price reaction, question or commentary framing.','false':'Only forecast/valuation/stock movement, advice, target-price/rating change, voluntary fund allocations/sentiment, future earnings/calendar, transcript, generic official inflation objective, vague teaser, routine product amenity, uncommitted hope/rumor or an existing-condition explainer without a discrete actual fact.'}}
QUESTIONS['screen']={'type':'choice','instructions':'Separate whether an article deserves deeper analysis from whether it is a trade. Keep genuine company/official macro events including actual rate decisions even holds, real earnings/result directions even without numbers, new legal/operating/control/capital/supply constraints, and specific new authoritative hike/cut signals. Look through framing to the actual supplied event. Drop pure advice/PT, preview, roundup/transcript, price tape, generic policy weather, rumor and small/local facts with no US/global-sector/listed channel. Do not invent missing events or assumed priced surprise. A small private local subsidiary or unrelated foreign telecom story is insufficient; an issuer result, financing or actual operations change merits deeper investigation.', 'criteria':{'investigate':'An actual specific event/result with a plausible listed/US/global-sector mechanism merits deeper analysis, even if the price moved the other way or commentary surrounds it.','discard':'No concrete underlying event/result; only tape/color/advice/preview/rumor/reprint, packaging, local irrelevant private story or tiny amenity/subsidiary.'}}


QUESTIONS['path_signal']={'type':'noul','instructions':'Does an empowered central-bank/government actor give a specific policy-path signal in this headline? This asks what was said, not whether rates already changed. Treat explicit hike/cut possibilities as signals; do not downgrade them merely because they are conditional.', 'criteria':{'true':'A Fed/central-bank chair, governor, voting official or rate panel says hikes/cuts may be needed, sees scope for more hikes/cuts, leaves the door open for a specified rate move, signals impending hikes/cuts, or says a rate increase is possible/needed. Also an actual signed/announced official rate/trade/fiscal decision. A named institution or its authorized officials can be the actor.','false':'Only an analyst/strategist or market odds predicting rates; generic inflation too high, pledges to tame inflation, pivotal moment, puts nation on alert, expert warnings, lawmakers urging, or an unspecified speech without a concrete rate/action path.'}}
QUESTIONS['form']={'type':'choice','instructions':'What does the headline itself provide? A direct actual result/action can appear inside reaction or advice wording. A passing mention of earnings or an old event is insufficient. Distinguish actual beat/miss/growth/guidance/corporate/legal facts from only price after earnings. Do not invent missing facts.', 'criteria':{'event_main':'An actual specific underlying event/result is supplied, including earnings beat/miss/growth, official data direction, guidance revision, binding deal, approval, leadership or operational/legal change, or a specific authorized rate-path signal.','recycled':'A feature, opinions on a previous earnings report, how an already-known event changed things, what we know about an old recall/case, generic existing regime, or a causal price narrative with no stated actual result/change.','packaging':'Roundup/list of multiple unrelated news items/earnings movers, transcript/call highlights/summary, upcoming earnings/calendar, pure price target/picks or vague teaser without an actual underlying event/result.'}}

QUESTIONS['eligibility']={'type':'choice','instructions':'Audit the underlying event and its transmission separately from salience. Select qualifying only when both are supplied. This is binary hop-0 screening, not a Lane event class or a trade. A new actual company/official result can be in-line, and an empowered official explicitly saying hikes/cuts may be needed is a concrete policy-path signal. Do not invent surprise, held names, completion, a trial outcome or prior-event history.', 'criteria':{
 'qualifying':'A specific new binding action, actual released company result/guidance, official macro print, actual legal/regulatory decision, clinical outcome, capital/control/capacity change, disruption, named forced flow, or concrete authorized rate path has a relevant channel. Named listed foreign issuers qualify for deeper analysis; do not blanket-veto foreign earnings or firm actions. US macro, major cross-market economy data, US legal/trade rules, real global commodity supply, substantial US infrastructure or systemic AI industry commitments qualify. A named drug/company actual readout or US FDA approval is a fact; price/advice framing does not erase a stated actual result. New buyback authorization/expansion or a specified completed capital return qualifies.',
 'not_new':'Only existing status/regime, a historical FDA approval dated well before this article, reaffirmed unchanged guidance/midpoint, routine tranche/status update under an already-announced buyback, old-case discussion or reaction to an old fact, speeches/objectives with no specific path, or an explainer about what buybacks/earnings/tariffs mean. Do not assume every event is old; require evidence of recycling.',
 'not_a_fact':'Only an earnings estimate/calendar/preview, vague unspecified result/teaser or unnamed treatment with no identifiable issuer/drug/channel, hoped-for decision, talks/working group, proposed bill, lawmakers urging, court arguments without a new ruling/filing, a trial starting/first patient dosed without outcome data, a company resubmitting an application without an actual regulator decision, or rumored financing. FDA granting formal priority review to a named issuer changes its review clock; seeking approval is not approval. A new official company forecast is guidance; an analyst revenue estimate is not.',
 'out_of_book':'An actual but unlinked small private/local business event, minor private foreign airline/fintech restructuring, local hospital portal/hack, foreign domestic GDP/CPI/debt without a major US/cross-market or stated global commodity channel, private small venture finance even with famous investors, routine junior administrative hires/auditor changes, individual/crime sanctions or personal lawsuits with no market pipe. An important noun, large sounding percentage or politician alone does not establish transmission. A private systemic AI supplier or multibillion-dollar global commodity funding commitment may qualify; ordinary private startup funding does not.',
 'packaging':'The actual story is price tape (including mortgage rates, bond yields, fund inflows, voluntary portfolio allocations or trading turnover), valuation/advice/PT without an actual issuer print, stock registry/financial indicator webpage, transcript, roundup of unrelated facts, conference/webinar/earnings preview, amenities/prototype/product promotion, or general color. A stated actual official data direction, corporate deal or legal decision inside a price wrapper can qualify; merely after earnings/data or amid inflation cannot.'}}

THRESHOLDS={'q5':.35,'action':.65,'print':.65,'policy_path':.65,'reported_fact':.50,'path_signal':.80,'screen':.85,'mechanism':.20,'junk':.90,'rumor':.60,'weather':.85,'eligibility':.20,'eligibility_override':.85}
ARTIFACT=re.compile(r'(?i)earnings call (?:transcript|highlights|summary)|morning squawk|\b\d+ key items shaping|earnings live updates|\bopinions on\b|what we know about|today.s news:|lead earnings movers')
BARE_CALENDAR=re.compile(r'(?i)^.{1,100}\b(?:Q[1-4]\s+(?:FY)?20\d{2}|FQ[1-4]\s+20\d{2})\s+earnings(?:\s+\([^)]*\))?$')
FORMULA='mechanism >= cutoff AND q5 junk/rumor/weather below veto thresholds AND any q5-change/action/print/policy_path/reported_fact/screen support above their respective thresholds'
def protocol_sha():return sha(dict(version=VERSION,contract=CONTRACT_VERSION,rubric=RUBRIC,questions=QUESTIONS,thresholds=THRESHOLDS,formula=FORMULA,retries=3,weather_override='path_signal >= .90 or eligibility_qualifying >= override',eligibility_gate='qualifying >= cutoff; strong qualifying may supply support; mechanism remains >= .10',form_veto=[.50,.70],artifacts=[ARTIFACT.pattern,BARE_CALENDAR.pattern]))
def decide(row,payload):
 answers=payload['answers'];s={}
 for key,q in QUESTIONS.items():
  a=answers[key]
  if a.get('type')!=q['type']:raise ValueError('answer type mismatch')
  if q['type']=='choice':
   probs=a['probabilities']
   if set(probs)!=set(q['criteria']):raise ValueError('incomplete probabilities')
   values=list(probs.values())
  else:values=[a['noul']]
  if any(isinstance(v,bool) or not isinstance(v,(int,float)) or not math.isfinite(v) or not 0<=v<=1 for v in values):raise ValueError('invalid probabilities')
  if q['type']=='choice':
   if abs(sum(values)-1)>.02 or a.get('choice') not in probs or probs[a['choice']]<max(values):raise ValueError('invalid choice')
   s.update(probs) if key=='q5' else s.update(screen=probs['investigate']) if key=='screen' else s.update({('eligibility_' if key=='eligibility' else 'form_')+k:v for k,v in probs.items()})
  else:s[key]=values[0]
 t=THRESHOLDS
 veto=next((key for key in ('junk','rumor','weather') if s[key]>=t[key] and not(key=='weather' and (s['path_signal']>=.90 or s['eligibility_qualifying']>=THRESHOLDS['eligibility_override']))),'')
 if s['form_packaging']>=.50 or s['form_recycled']>=.70:veto='packaging_or_recycled'
 if s['eligibility_qualifying']<t['eligibility']:veto='no_eligible_constraint'
 if ARTIFACT.search(row.get('title','')) or BARE_CALENDAR.search(row.get('title','')):veto='packaging_or_calendar'
 supported=s['eligibility_qualifying']>=t['eligibility_override'] or s['change']>=t['q5'] or any(s[k]>=t[k] for k in ('action','print','policy_path','reported_fact','screen','path_signal'))
 keep=not veto and (s['mechanism']>=t['mechanism'] or (s['eligibility_qualifying']>=t['eligibility_override'] and s['mechanism']>=.10)) and supported
 return dict(decision='keep' if keep else 'drop',reason=veto or ('constraint_change' if keep else 'no_supported_constraint'),policy_version=VERSION,protocol_sha256=protocol_sha(),model=payload.get('model','unknown'),answers=answers,signals=s,usage=payload.get('usage',{}),novelty_verified=bool(row.get('prior_events')))

def evaluate(row,poster,key):
 """Retry malformed/failed responses, never consult gold; retain charged usage."""
 from .jev_gate import make_state
 usage={};last=None
 for attempt in range(3):
  try:
   payload=poster(make_state(row),QUESTIONS,key)
   for k,v in payload.get('usage',{}).items():
    if isinstance(v,(int,float)):usage[k]=usage.get(k,0)+v
   result=decide(row,payload);result.update(usage=usage,retry_count=attempt)
   return result
  except Exception as exc:last=exc
 raise RuntimeError('Lane evaluation failed after 3 attempts: '+type(last).__name__+': '+str(last)[:160]) from last
